name: riada
description: Social sport app

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Common
  path: ^1.8.2
  intl: ^0.17.0
  shared_preferences: ^2.2.0
  decimal: ^2.3.2
  jiffy: ^5.0.0
  form_validator: ^2.1.1

  # UI
  cupertino_icons: ^1.0.5
  sizer: ^2.0.15
  table_calendar: ^3.0.8

  # Network
  http: ^0.13.5
  json_annotation: ^4.8.1

  # Image
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  image_picker: ^1.0.0
  flutter_image_compress: ^2.0.3

  # DI, Architecture & Routing
  get_it: ^7.6.0
  injectable: ^2.1.2
  flutter_bloc: ^8.1.3
  auto_route: ^7.7.0
  event_bus: ^2.0.0

  # Firebase
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.4
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  firebase_dynamic_links: ^5.3.3
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.3

  # Notification
  flutter_local_notifications: ^15.1.0+1

  # Misc
  url_launcher: ^6.1.8

dev_dependencies:
  # generator
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.2.0
  flutter_gen: ^5.3.1
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.6

  build_runner:
  flutter_gen_runner:

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons:
  image_path: "assets/images/icon.jpg"
  android: true
  ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
